version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.8  # Imagem base do CircleCI
    steps:
      - checkout

      - setup_remote_docker:
          version: 19.03.12  # Versão compatível do Docker

      - run:
          name: Construir imagem do Apache Airflow
          command: |
            # Suponha que o Dockerfile para a imagem do Apache Airflow esteja no diretório 'docker'
            cd docker
            docker build -t my-airflow-image:latest .

      - checkout

      - run:
          name: Build da imagem do ambiente do MWAA Local
          command: ./mwaa-local-env build-image

      - run:
          name: Testar requisitos do ambiente do MWAA Local
          command: ./mwaa-local-env test-requirements

      - run:
          name: Empacotar requisitos do ambiente do MWAA Local
          command: ./mwaa-local-env package-requirements

      - run:
          name: Iniciar ambiente do MWAA Local
          command: ./mwaa-local-env start &


      - run:
          name: Verificar se o pytest está instalado
          command: |
            docker exec -it $CIRCLE_CONTAINER_ID python -m pytest --version
            if [ $? -eq 0 ]; then
              echo "pytest is installed"
            else
              echo "pytest is not installed"
            fi

      - run:
          name: Verificar se o unittest está instalado
          command: |
            docker exec -it $CIRCLE_CONTAINER_ID python -m unittest --version
            if [ $? -eq 0 ]; then
              echo "unittest is installed"
            else
              echo "unittest is not installed"
            fi

workflows:
  version: 2
  build:
    jobs:
      - build
