version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.10  # Use a versão desejada do Python
    steps:
      - checkout

      - run:
          name: Instalar dependências
          command: |
            export AIRFLOW_HOME=~/airflow
            echo $AIRFLOW_HOME
            export AIRFLOW__CORE__DAGS_FOLDER=apache-airflow/dags
            sudo apt-get update
            sudo apt-get install -y python3-pip
            sudo apt-get install -y mariadb-client-core-10.5 
            pip3 install apache-airflow

            airflow db init
            airflow db check

      - run:
          name: Testar a DAG e a tarefa específica
          command: airflow tasks test hello_world_dag hello_task

workflows:
  version: 2
  build:
    jobs:
      - build
