version: 2.1
jobs:
  build:
    docker:
      - image: amazon/mwaa-local:2_6

    steps:
      - checkout

      - run:
          name: Instalar Python 3 e dependências
          command: |
            yum install -y python3

workflows:
  version: 2
  build:
    jobs:
      - build
