version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.10  # Python 3.10

    steps:
      - checkout

      - run:
          name: Instalar dependências
          command: |
            export AIRFLOW_HOME=~/airflow
            echo $AIRFLOW_HOME
            sudo apt-get update
            sudo apt-get install -y python3-pip
            pip3 install 'apache-airflow==2.6.3'  # Apache Airflow 2.6.3

            airflow db check

      - run:
          name: DAGS
          command: |
            ls
            cd dags  # Correção no comando para entrar na pasta dags
            ls

      - run:
          name: Testar a DAG e a tarefa específica
          command: airflow tasks test hello_world_dag hello_task

workflows:
  version: 2
  build:
    jobs:
      - build