version: 2.1
jobs:
  build:
    docker:
      - image: python:3.7

    steps:
      - checkout

      - run:
          name: Instalar Python e dependências
          command: |
            # Atualize o pip para a versão mais recente
            pip install --upgrade pip

            # Instale as bibliotecas do sistema necessárias para o Apache Airflow
            apt-get update
            apt-get install -y --no-install-recommends \
                build-essential \
                libssl-dev \
                libffi-dev

            # Instale o Apache Airflow
            pip install apache-airflow==2.5.2

            # Instale as bibliotecas listadas no requirements.txt
            pip install -r requirements/requirements.txt


workflows:
  version: 2
  build:
    jobs:
      - build
