version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.8 

    steps:
      - checkout

      - run:
          name: Instalar dependências
          command: |
            export AIRFLOW_HOME=~/airflow
            echo $AIRFLOW_HOME
            apt-get update
            apt-get install -y python3-pip
            pip3 install apache-airflow
            airflow db init
            airflow db check

      - run:
          name: DAGS
          command: |
            ls
            cd ~/airflow
            ls
            cd/dags
            ls

      - run:
          name: Testar a DAG e a tarefa específica
          command: airflow tasks test hello_world_dag hello_task

workflows:
  version: 2
  build:
    jobs:
      - build
