version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.8  # Imagem base do CircleCI
    steps:
      - checkout

      - setup_remote_docker:
          version: 19.03.12  # Versão compatível do Docker

      - run:
          name: Build da imagem do ambiente do MWAA Local
          command: ./mwaa-local-env build-image

      - run:
          name: Testar requisitos do ambiente do MWAA Local
          command: ./mwaa-local-env test-requirements

      - run:
          name: Empacotar requisitos do ambiente do MWAA Local
          command: ./mwaa-local-env package-requirements

      - run:
          name: Iniciar ambiente do MWAA Local
          command: ./mwaa-local-env start

      - run:
          name: Verificar se o pytest está instalado
          command: docker exec -it aws-mwaa-local-runner-2_6-local-runner-1 /bin/bash -c "ls"



workflows:
  version: 2
  build:
    jobs:
      - build